Switch from poetry to uv
commaai/agnos-builder pull request #238
Opened 2024-07-11 10:15 UTC by pantew869

Fixes #232

2024-07-13 20:12 UTC, adeebshihadeh commented
Doing a test build now. Would also be nice to switch pyenv to uv.

2024-07-13 20:17 UTC, adeebshihadeh requested changes

2024-07-13 20:17 UTC, adeebshihadeh commented on userspace/pyproject.toml
> +    "sconscontrib",
make sure to use two spaces

2024-07-13 20:17 UTC, adeebshihadeh commented on userspace/pyproject.toml
> +    "ipython",
same here

2024-07-13 20:17 UTC, adeebshihadeh commented on .pre-commit-config.yaml
> --   repo: https://github.com/python-poetry/poetry
is there a uv equivalent?

2024-07-14 13:38 UTC, pantew869 commented on .pre-commit-config.yaml
> --   repo: https://github.com/python-poetry/poetry
Afaik no

2024-07-14 14:29 UTC, merged